//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Site", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        internal static string Cadastrar {
            get {
                return ResourceManager.GetString("Cadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrinho.
        /// </summary>
        internal static string Carrinho {
            get {
                return ResourceManager.GetString("Carrinho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias.
        /// </summary>
        internal static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar.
        /// </summary>
        internal static string Comprar {
            get {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        internal static string Compras {
            get {
                return ResourceManager.GetString("Compras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Produtos.
        /// </summary>
        internal static string GerenciarProdutos {
            get {
                return ResourceManager.GetString("GerenciarProdutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens.
        /// </summary>
        internal static string Itens {
            get {
                return ResourceManager.GetString("Itens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguagem.
        /// </summary>
        internal static string Linguagem {
            get {
                return ResourceManager.GetString("Linguagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Desejos.
        /// </summary>
        internal static string ListadeDesejos {
            get {
                return ResourceManager.GetString("ListadeDesejos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista.
        /// </summary>
        internal static string ListaDesejos {
            get {
                return ResourceManager.GetString("ListaDesejos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        internal static string Produtos {
            get {
                return ResourceManager.GetString("Produtos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string Sobre {
            get {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }
    }
}
